<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <PlatformTarget>x64</PlatformTarget>
    <OutputType>Library</OutputType>
    <AssemblyName>RevitWebAppSync</AssemblyName>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="RevitAPI">
      <HintPath>C:\Program Files\Autodesk\Revit 2026\RevitAPI.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="RevitAPIUI">
      <HintPath>C:\Program Files\Autodesk\Revit 2026\RevitAPIUI.dll</HintPath>
      <Private>False</Private>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\revitSync.png" />
    <EmbeddedResource Include="Resources\revitSave.png" />
  </ItemGroup>

  <!-- Post-build events -->
  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Copy SourceFiles="$(ProjectDir)RevitWebAppSync.addin" 
          DestinationFolder="$(APPDATA)\Autodesk\Revit\Addins\2026\" 
          Condition="Exists('$(APPDATA)\Autodesk\Revit\Addins\2026\')" />
    
    <Copy SourceFiles="$(TargetPath)" 
          DestinationFolder="$(APPDATA)\Autodesk\Revit\Addins\2026\" 
          Condition="Exists('$(APPDATA)\Autodesk\Revit\Addins\2026\')" />
  </Target>

</Project>