#!/usr/bin/env python3
"""Generate BinaVibe/Mcp/Tools/ToolManifest.g.cs from ToolRegistry.cs.

The installed-capability manifest the add-in sends to the backend
(spec §8.2) must be derived from the real dispatch table, never typed by
hand. Parses the arms of the FIRST `tool switch` in ToolRegistry.Invoke
(up to `_ => NotImplemented(tool)`); nested `category switch` blocks are
not tools. Tests/ToolManifestTests.cs fails if this file is stale.

Usage:  python3 scripts/gen-tool-manifest.py   (from the repo root)
"""
from __future__ import annotations

import hashlib
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "BinaVibe" / "Mcp" / "Tools" / "ToolRegistry.cs"
OUT = ROOT / "BinaVibe" / "Mcp" / "Tools" / "ToolManifest.g.cs"
PROTOCOL_VERSION = 2


def arms(src: str) -> list[str]:
    start = src.index("return tool switch")
    end = src.index("_ => NotImplemented(tool)", start)
    block = src[start:end]
    names = re.findall(r'^\s*"([a-z][a-z0-9_]+)"\s*=>', block, flags=re.M)
    dups = {n for n in names if names.count(n) > 1}
    if dups:
        sys.exit(f"duplicate switch arms: {sorted(dups)}")
    return sorted(set(names))


def main() -> None:
    names = arms(SRC.read_text(encoding="utf-8"))
    version = hashlib.sha256("\n".join(names).encode("utf-8")).hexdigest()[:12]
    body = ",\n".join(f'            "{n}"' for n in names)
    OUT.write_text(
        "// <auto-generated>\n"
        "// GENERATED by scripts/gen-tool-manifest.py from ToolRegistry.cs — do not edit.\n"
        "// Spec: bina-ai docs/superpowers/specs/2026-08-14-control-plane-rewrite-design.md §8.2\n"
        "// </auto-generated>\n"
        "namespace BinaVibe.Mcp.Tools\n"
        "{\n"
        "    /// <summary>What THIS add-in build actually dispatches. Sent on every\n"
        "    /// /tool/generate env header (protocol_version, manifest_version,\n"
        "    /// installed_tools) and in the MCP tunnel `ready` frame; the backend\n"
        "    /// intersects it with its own manifest and the tenant's entitlement.</summary>\n"
        "    public static class InstalledToolManifest\n"
        "    {\n"
        f"        public const int ProtocolVersion = {PROTOCOL_VERSION};\n"
        f"        public const string Version = \"{version}\";\n"
        f"        public static readonly string[] Names = new string[]\n"
        "        {\n"
        f"{body}\n"
        "        };\n"
        "    }\n"
        "}\n",
        encoding="utf-8",
    )
    print(f"wrote {OUT.relative_to(ROOT)}: {len(names)} tools, version {version}")


if __name__ == "__main__":
    main()
