# engine-boot.ps1 — Bring the BINA Copilot Engine back up automatically at Windows
# logon, with ZERO user interaction. Registered as an ONLOGON Scheduled Task by the
# installer (RevitCopilot.iss [Run]). Runs hidden; no console, no focus steal.
#
# Idempotent by design: if an engine is already answering on the loopback port
# (left by a prior Revit session, or the addin spawned it first), this exits
# immediately and lets the existing one own the port.
#
# Env contract: this mirrors EXACTLY what the addin's EngineManager passes to the
# engine (revit-addin-sync/Services/EngineManager.cs spawn path), and it sources
# every value from the SAME single source of truth the addin uses
# (%APPDATA%\RevitWebAppSync\config.json). So a boot-started engine and an
# addin-started engine always agree on secret, gateway and token.
#
# Security note: the engine secret lives in config.json (plaintext, user-scoped
# %APPDATA%) — that is pre-existing addin behaviour (BinaConfig persists
# EngineSecret there). We reuse it rather than invent a parallel secret store, so
# the boot path never disagrees with the addin about credentials.

$ErrorActionPreference = 'SilentlyContinue'

$engineRoot = Join-Path $env:LOCALAPPDATA 'Bina\RevitSync\engine'
$configPath = Join-Path $env:APPDATA 'RevitWebAppSync\config.json'
$healthPort  = if ($env:BINA_ENGINE_PORT) { $env:BINA_ENGINE_PORT } else { '48810' }

# Nothing to do if the addin config is missing, or the user hasn't minted a
# gateway device token yet (no login / no gateway configured). The addin spawns
# the engine itself the moment it has both — so at logon we simply wait.
if (-not (Test-Path $configPath)) { exit 0 }
$cfg = Get-Content -Raw $configPath | ConvertFrom-Json
if (-not $cfg.DeviceToken -or -not $cfg.GatewayUrl) { exit 0 }   # not gateway-configured yet

# EngineSecret is auto-generated by the addin if blank, so it should always be
# present; if it somehow isn't, the engine's config.py refuses to start anyway.
if (-not $cfg.EngineSecret) { exit 0 }

# Already healthy? Reuse it (same probe EngineManager uses).
try {
    $healthy = Invoke-RestMethod -Uri "http://127.0.0.1:$healthPort/health" -TimeoutSec 2
    if ($healthy.engine -eq $true) { exit 0 }
} catch { }

# Pick the NEWEST installed engine bundle by semver — mirrors
# EngineManager.NewestEngineLauncher: highest engine_version under engine\<ver>\ wins,
# and the updater never prunes, so newest-on-disk is always the version to run.
$versions = @()
Get-ChildItem -Path $engineRoot -Directory -ErrorAction SilentlyContinue | ForEach-Object {
    $manifest = Join-Path $_.FullName 'engine-version.json'
    if (Test-Path $manifest) {
        try {
            $v = (Get-Content -Raw $manifest | ConvertFrom-Json).engine_version
            if ($v) { $versions += [pscustomobject]@{ Version = $v; Dir = $_.FullName } }
        } catch { }
    }
}
if ($versions.Count -eq 0) { exit 0 }   # no engine installed
$newest = $versions | Sort-Object -Property @{ Expression = { [version]($_.Version) } } -Descending | Select-Object -First 1
$launcher = Join-Path $newest.Dir 'run-engine.cmd'
if (-not (Test-Path $launcher)) { exit 0 }

# ---- Build the child process with the same env the addin hand-passes ----
$psi = New-Object System.Diagnostics.ProcessStartInfo
$psi.FileName      = 'cmd.exe'
$psi.Arguments     = "/c `"$launcher`""
$psi.UseShellExecute = $false
$psi.CreateNoWindow  = $true
$psi.WorkingDirectory = $newest.Dir

$psi.EnvironmentVariables['BINA_ENGINE']         = '1'
$psi.EnvironmentVariables['BINA_ENGINE_SECRET']  = [string]$cfg.EngineSecret
$psi.EnvironmentVariables['BINA_ENGINE_PORT']    = $healthPort
$psi.EnvironmentVariables['BINA_GATEWAY_URL']    = [string]$cfg.GatewayUrl
$psi.EnvironmentVariables['BINA_ENGINE_TOKEN']   = [string]$cfg.DeviceToken

# Langfuse tracing via the GATEWAY proxy only — the engine holds no Langfuse
# creds (poison-pill). Same three vars EngineManager sets (EngineManager.cs:191-197).
$psi.EnvironmentVariables['LANGFUSE_BASE_URL']   = ([string]$cfg.GatewayUrl).TrimEnd('/') + '/gateway/langfuse'
$psi.EnvironmentVariables['LANGFUSE_PUBLIC_KEY'] = [string]$cfg.DeviceToken
$psi.EnvironmentVariables['LANGFUSE_SECRET_KEY'] = 'engine'

# Poison-pill parity: strip any provider keys that a developer shell might have,
# so the engine never sees a provider key in gateway mode (config.py refuses to
# start otherwise). Harmless no-op on clean machines.
foreach ($k in @('DEEPSEEK_API_KEY','OPENAI_API_KEY','AZURE_OPENAI_API_KEY','GATEWAY_UPSTREAM_KEY')) {
    [void]$psi.EnvironmentVariables.Remove($k)
}

$proc = [System.Diagnostics.Process]::Start($psi)

# Write the pidfile so EngineManager.KillStaleFromPidFile can find and reap a
# boot-started engine in a later session that died/crashed (same path as the
# addin's own spawn: engine\engine.pid).
if ($proc) {
    Set-Content -Path (Join-Path $engineRoot 'engine.pid') -Value $proc.Id -Encoding Ascii
    $proc.Close()
}
exit 0